### ISSUE TITLE
Support LaTeX syntax of using `\(\)` for inline math and `\[\]` for block-level math

### ISSUE THREAD

**Issue by dousha** [UziTech/marked-katex-extension#280]
I have some documents that use `$` for other purposes so to avoid conflicts, the math expressions are quoted with `\( ... \)`. I believe it is a common use case so I am planning to add support for it.

I am currently implementing this change. A PR will be opened later.

**Comment by UziTech** [comment]
It is already possible to prevent katex from rendering due to a `$` if you escape it.

```md
\$ this is not katex $
```

**Comment by UziTech** [comment]
If you would like to create a separate extension that uses `()` and `[]` instead of `$` and `$$` you can copy this one and change it to use those symbols and release it under another name but I am not interested in having multiple ways to write katex in this extension. I like keeping the extensions simple instead of providing multiple ways to do something.

**Comment by dousha** [comment]
Yes. I am aware that by escaping the `$` it would be treated as a normal dollar sign. It's more of a MathJax/tex2jax compatibility where `\( \)` are used as the default inline math expression.

Thanks for your advice. I understand that we should keep it simple.

**Comment by Al-phonsio** [comment]
I am converting markdown from different sources that sometimes use $ / $$ and sometimes \( \[. 
It would be great if this extension would support both delimiters.

**Comment by UziTech** [comment]
@Al-phonsio Why would that be better than using two extensions?

**Comment by UziTech** [comment]
See https://github.com/UziTech/marked-katex-extension/issues/280#issuecomment-1807527690

This issue is closed because it would essentially require extra code that essentially everyone who uses this extension wont use. I suggest forking this extension and creating a second extension that supports `()`. That way people can opt in to either or both of the delimiters by installing the extension they need.
